### ISSUE TITLE
Reservierung schlägt fehl

### ISSUE THREAD

**Issue by kimberlycas** [hhu-propra2/ProPay#1]
- habe 2 Testaccounts erstellt und diese mit Geld aufgeladen
- wenn ich nun einen Betrag von acc1 auf acc2 reservieren möchte, kommt folgende Fehlermeldung:

```
{
  "timestamp": "2019-02-13T11:24:59.675+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : de.hhu.propra2.propay.entities.Reservation.targetAccount -> de.hhu.propra2.propay.entities.Account; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : de.hhu.propra2.propay.entities.Reservation.targetAccount -> de.hhu.propra2.propay.entities.Account",
  "path": "/reservation/reserve/test/acc2"
}
```

**Comment by pointbazaar** [comment]
wir haben auch nen fehler wenn wir was reservieren wollen

**Comment by n2o** [comment]
Hm, ich kann das nicht reproduzieren... Könnt ihr ein Beispiel liefern mit curl?

Beispielsweise:

```bash
curl -X POST "https://propra-propay.herokuapp.com/account/accounty/?amount=100"
{"account":"accounty","amount":100.0,"reservations":[]}

curl -X POST "https://propra-propay.herokuapp.com/account/accountus/?amount=200"       
{"account":"accountus","amount":200.0,"reservations":[]}

curl -X POST "https://propra-propay.herokuapp.com/reservation/reserve/accounty/accountus/?amount=50"
{"id":157,"amount":50.0}
```

**Comment by pointbazaar** [comment]
@n2o Es liegt daran, dass du erstmal 200 auf "accountus" ueberweist. wenn du das nicht machst kommt der fehler. Wenn man erst ueberweisen muss, damit der account dem system beitritt, ist alles in ordnung aber sollte man nicht auch dem system beitreten koennen ohne erstmal geld einzuzahlen?

**Comment by n2o** [comment]
Hm ja, gibt keine explizite Route dafur, geht aber so:

`curl -X POST "https://propra-propay.herokuapp.com/account/myawesomeaccount/?amount=0"`

**Comment by n2o** [comment]
Neue Accounts können nun mit leerem Guthaben mit der Route

`curl -X POST "https://propra-propay.herokuapp.com/account/<new-acc>"`

angelegt werden.

**Comment by n2o** [comment]
Wir konnten den Bug nun reproduzieren. Es gab ein Problem mit der GET Route um einen Account anzulegen. Sollte nun alles passen. Version 1.0.5 ist online.
